apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: dennisw81/udagram-api-user:v1
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          env:
            - name: POSTGRES_HOST
              value: "udagramdennisdevdb.cau82pb0khf5.us-west-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"
            - name: AWS_BUCKET
              value: "udagram-dennis-dev-bucket"
            - name: AWS_REGION
              value: "us-west-1"
            - name: AWS_PROFILE
              value: "default"
            - name: JWT_SECRET
              value: "testing"
            - name: URL
              value: "http://localhost:8100"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
